spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=evidhya_db
    username: sa
    password: Evidhya@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true